services:
  app:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped

  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    command: ["gosu", "user", "/opt/python/bin/python3", "./run.py", "--voicelib_dir", "/opt/voicevox_core/", "--runtime_dir", "/opt/onnxruntime/lib", "--host", "0.0.0.0", "--cors_policy_mode", "all"]
    ports:
      - "50021:50021"
    restart: unless-stopped
